// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI6g3wnwG4QFsDNKikKS_ZMU2qocD_hSY',
    appId: '1:616349335993:web:7edc939aef7fa4ef64b668',
    messagingSenderId: '616349335993',
    projectId: 'starpoints-d9368',
    authDomain: 'starpoints-d9368.firebaseapp.com',
    databaseURL: 'https://starpoints-d9368.firebaseio.com',
    storageBucket: 'starpoints-d9368.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqwUO06kklHtE7UE_ifC5TmoVeTPawiY4',
    appId: '1:616349335993:android:2876b6a479b0c71464b668',
    messagingSenderId: '616349335993',
    projectId: 'starpoints-d9368',
    databaseURL: 'https://starpoints-d9368.firebaseio.com',
    storageBucket: 'starpoints-d9368.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx1d5-6MuSzfPQ0aI536worjLZ7AHAgpE',
    appId: '1:616349335993:ios:e951b8c9dcbfd90064b668',
    messagingSenderId: '616349335993',
    projectId: 'starpoints-d9368',
    databaseURL: 'https://starpoints-d9368.firebaseio.com',
    storageBucket: 'starpoints-d9368.appspot.com',
    androidClientId: '616349335993-4t1rm70s7g3pgfpfhrhqfoatks7ahp58.apps.googleusercontent.com',
    iosClientId: '616349335993-jhelrhposmd1psh9c2m5tb4i9facst47.apps.googleusercontent.com',
    iosBundleId: 'br.com.bjbraz.myRootstockWallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx1d5-6MuSzfPQ0aI536worjLZ7AHAgpE',
    appId: '1:616349335993:ios:443ad068d04b3b8964b668',
    messagingSenderId: '616349335993',
    projectId: 'starpoints-d9368',
    databaseURL: 'https://starpoints-d9368.firebaseio.com',
    storageBucket: 'starpoints-d9368.appspot.com',
    androidClientId: '616349335993-4t1rm70s7g3pgfpfhrhqfoatks7ahp58.apps.googleusercontent.com',
    iosClientId: '616349335993-6umoqvthf33b0p0s6gihnb8gfm9d8aco.apps.googleusercontent.com',
    iosBundleId: 'br.com.bjbraz.myRootstockWallet.RunnerTests',
  );
}
